apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nodeapp-devolopment
  labels:
    app: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        imagePullPolicy: Always
        env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-uri
                key: OPENAI_API_KEY
