apiVersion: v1
kind: Secret
metadata:
  name: mongocredentials
  namespace: dev
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly90aGlsaW5hOm45QXZlRE5sOUl6elRybldAY2x1c3Rlci1uZXcudXF3dXNmbC5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5